const noteBaseUrl = '@/assets/piano/';

export default [
    {id: 1, name: "C2", url: noteBaseUrl + "a49.mp3", type: true, hover: false},
    {id: 2, name: "C#2", url: noteBaseUrl + "b49.mp3", hove: false},
    {id: 3, name: "D2", url: noteBaseUrl + "a50.mp3", type: true, hover: false},
    {id: 4, name: "D#2", url: noteBaseUrl + "b50.mp3", hove: false},
    {id: 5, name: "E2", url: noteBaseUrl + "a51.mp3", type: false, hover: false},
    {id: 6, name: "F2", url: noteBaseUrl + "a52.mp3", type: true, hover: false},
    {id: 7, name: "F#2", url: noteBaseUrl + "b52.mp3", hove: false},
    {id: 8, name: "G2", url: noteBaseUrl + "a53.mp3", type: true, hover: false},
    {id: 9, name: "G#2", url: noteBaseUrl + "b53.mp3", hove: false},
    {id: 10, name: "A2", url: noteBaseUrl + "a54.mp3", type: true, hover: false},
    {id: 11, name: "A#2", url: noteBaseUrl + "b54.mp3", hove: false},
    {id: 12, name: "B2", url: noteBaseUrl + "a55.mp3", type: false, hover: false},
    {id: 13, name: "C3", url: noteBaseUrl + "a56.mp3", type: true, hover: false},
    {id: 14, name: "C#3", url: noteBaseUrl + "b56.mp3", hove: false},
    {id: 15, name: "D3", url: noteBaseUrl + "a57.mp3", type: true, hover: false},
    {id: 16, name: "D#3", url: noteBaseUrl + "b57.mp3", hove: false},
    {id: 17, name: "E3", url: noteBaseUrl + "a48.mp3", type: false, hover: false},
    {id: 18, name: "F3", url: noteBaseUrl + "a81.mp3", type: true, hover: false},
    {id: 19, name: "F#3", url: noteBaseUrl + "b81.mp3", hove: false},
    {id: 20, name: "G3", url: noteBaseUrl + "a87.mp3", type: true, hover: false},
    {id: 21, name: "G#3", url: noteBaseUrl + "b87.mp3", hove: false},
    {id: 22, name: "A3", url: noteBaseUrl + "a69.mp3", type: true, hover: false},
    {id: 23, name: "A#3", url: noteBaseUrl + "b69.mp3", hover: false},
    {id: 24, name: "B3", url: noteBaseUrl + "a82.mp3", type: false, hover: false},
    {id: 25, name: "C4", url: noteBaseUrl + "a84.mp3", type: true, hover: false},
    {id: 26, name: "C#4", url: noteBaseUrl + "b84.mp3", hover: false},
    {id: 27, name: "D4", url: noteBaseUrl + "a89.mp3", type: true, hover: false},
    {id: 28, name: "D#4", url: noteBaseUrl + "b89.mp3", hover: false},
    {id: 29, name: "E4", url: noteBaseUrl + "a85.mp3", type: false, hover: false},
    {id: 30, name: "F4", url: noteBaseUrl + "a73.mp3", type: true, hover: false},
    {id: 31, name: "F#4", url: noteBaseUrl + "b73.mp3", hover: false},
    {id: 32, name: "G4", url: noteBaseUrl + "a79.mp3", type: true, hover: false},
    {id: 33, name: "G#4", url: noteBaseUrl + "b79.mp3", hover: false},
    {id: 34, name: "A4", url: noteBaseUrl + "a80.mp3", type: true, hover: false},
    {id: 35, name: "A#4", url: noteBaseUrl + "b80.mp3", hover: false},
    {id: 36, name: "B4", url: noteBaseUrl + "a65.mp3", type: false, hover: false},
    {id: 37, name: "C5", url: noteBaseUrl + "a83.mp3", type: true, hover: false},
    {id: 38, name: "C#5", url: noteBaseUrl + "b83.mp3", hover: false},
    {id: 39, name: "D5", url: noteBaseUrl + "a68.mp3", type: true, hover: false},
    {id: 30, name: "D#5", url: noteBaseUrl + "b68.mp3", hover: false},
    {id: 41, name: "E5", url: noteBaseUrl + "a70.mp3", type: false, hover: false},
    {id: 42, name: "F5", url: noteBaseUrl + "a71.mp3", type: true, hover: false},
    {id: 43, name: "F#5", url: noteBaseUrl + "b71.mp3", hover: false},
    {id: 44, name: "G5", url: noteBaseUrl + "a72.mp3", type: true, hover: false},
    {id: 45, name: "G#5", url: noteBaseUrl + "b72.mp3", hover: false},
    {id: 46, name: "A5", url: noteBaseUrl + "a74.mp3", type: true, hover: false},
    {id: 47, name: "A#5", url: noteBaseUrl + "b74.mp3", hover: false},
    {id: 48, name: "B5", url: noteBaseUrl + "a75.mp3", type: false, hover: false},
    {id: 49, name: "C6", url: noteBaseUrl + "a76.mp3", type: true, hover: false},
    {id: 40, name: "C#6", url: noteBaseUrl + "b76.mp3", hover: false},
    {id: 51, name: "D6", url: noteBaseUrl + "a90.mp3", type: true, hover: false},
    {id: 52, name: "D#6", url: noteBaseUrl + "b90.mp3", hover: false},
    {id: 53, name: "E6", url: noteBaseUrl + "a88.mp3", type: false, hover: false},
    {id: 54, name: "F6", url: noteBaseUrl + "a67.mp3", type: true, hover: false},
    {id: 55, name: "F#6", url: noteBaseUrl + "b67.mp3", hover: false},
    {id: 56, name: "G6", url: noteBaseUrl + "a86.mp3", type: true, hover: false},
    {id: 57, name: "G#6", url: noteBaseUrl + "b86.mp3", hover: false},
    {id: 58, name: "A6", url: noteBaseUrl + "a66.mp3", type: true, hover: false},
    {id: 59, name: "A#6", url: noteBaseUrl + "b66.mp3", hover: false},
    {id: 60, name: "B6", url: noteBaseUrl + "a78.mp3", type: false, hover: false}
];


export const NotesMap = [
  { name: 'C2', file: 'a49.mp3' },
  { name: 'D2', file: 'a50.mp3' },
  { name: 'E2', file: 'a51.mp3' },
  { name: 'F2', file: 'a52.mp3' },
  { name: 'G2', file: 'a53.mp3' },
  { name: 'A2', file: 'a54.mp3' },
  { name: 'B2', file: 'a55.mp3' },
  { name: 'C3', file: 'a56.mp3' },
  { name: 'D3', file: 'a57.mp3' },
  { name: 'E3', file: 'a48.mp3' },
  { name: 'F3', file: 'a81.mp3' },
  { name: 'G3', file: 'a87.mp3' },
  { name: 'A3', file: 'a69.mp3' },
  { name: 'B3', file: 'a82.mp3' },
  { name: 'C4', file: 'a84.mp3' },
  { name: 'D4', file: 'a89.mp3' },
  { name: 'E4', file: 'a85.mp3' },
  { name: 'F4', file: 'a73.mp3' },
  { name: 'G4', file: 'a79.mp3' },
  { name: 'A4', file: 'a80.mp3' },
  { name: 'B4', file: 'a65.mp3' },
  { name: 'C5', file: 'a83.mp3' },
  { name: 'D5', file: 'a68.mp3' },
  { name: 'E5', file: 'a70.mp3' },
  { name: 'F5', file: 'a71.mp3' },
  { name: 'G5', file: 'a72.mp3' },
  { name: 'A5', file: 'a74.mp3' },
  { name: 'B5', file: 'a75.mp3' },
  { name: 'C6', file: 'a76.mp3' },
  { name: 'D6', file: 'a90.mp3' },
  { name: 'E6', file: 'a88.mp3' },
  { name: 'F6', file: 'a67.mp3' },
  { name: 'G6', file: 'a86.mp3' },
  { name: 'A6', file: 'a66.mp3' },
  { name: 'B6', file: 'a78.mp3' },
  { name: 'C7', file: 'a77.mp3' },

  { name: 'C#2', file: 'b49.mp3' },
  { name: 'D#2', file: 'b50.mp3' },
  { name: 'F#2', file: 'b52.mp3' },
  { name: 'G#2', file: 'b53.mp3' },
  { name: 'A#2', file: 'b54.mp3' },
  { name: 'C#3', file: 'b56.mp3' },
  { name: 'D#3', file: 'b57.mp3' },
  { name: 'F#3', file: 'b81.mp3' },
  { name: 'G#3', file: 'b87.mp3' },
  { name: 'A#3', file: 'b69.mp3' },
  { name: 'C#4', file: 'b84.mp3' },
  { name: 'D#4', file: 'b89.mp3' },
  { name: 'F#4', file: 'b73.mp3' },
  { name: 'G#4', file: 'b79.mp3' },
  { name: 'A#4', file: 'b80.mp3' },
  { name: 'C#5', file: 'b83.mp3' },
  { name: 'D#5', file: 'b68.mp3' },
  { name: 'F#5', file: 'b71.mp3' },
  { name: 'G#5', file: 'b72.mp3' },
  { name: 'A#5', file: 'b74.mp3' },
  { name: 'C#6', file: 'b76.mp3' },
  { name: 'D#6', file: 'b90.mp3' },
  { name: 'F#6', file: 'b67.mp3' },
  { name: 'G#6', file: 'b86.mp3' },
  { name: 'A#6', file: 'b66.mp3' }
]